name: statsd
version: 1.0.0
description: StatsD client for Dart
homepage: https://github.com/pulyaevskiy/dart-statsd

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.0.2

dev_dependencies:
  test: ^1.17.12
